### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by nobody43** [p1r473/bitrot#3]
Hi. Thanks for the work. I understand this is a personal project and you are doing what you want there, so I will just point out why this tool will be used by less people:

- pip dependencies reduces portability, like: `progressbar` and `pushbullet`
- `pushbullet` is [deprecated](https://github.com/richard-better/pushbullet.py)
- using SaS to manage local files? hmmm
- some module binds a socket right after start, maybe move it to optional branches?

**Comment by p1r473** [comment]
Thanks for the tips. I used this project to teach myself python.

**Comment by p1r473** [comment]
What is SaS?

**Comment by nobody43** [comment]
I meant SaaS - [Software as a Service](https://www.gnu.org/philosophy/who-does-that-server-really-serve.html). Utilizing them limits your options and forces you to take unfavorable decisions.

> Thanks for the tips. I used this project to teach myself python.

It got some traction as you can see.
